name:                hoge3
version:             0.1.0.0
github:              "sky-y/hoge3"
license:             BSD3
author:              "Yuki Fujiwara"
maintainer:          "sky.y.0079@gmail.com"
copyright:           "Copyright: (c) 2018 Yuki Fujiwara"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/sky-y/hoge3#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hoge3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hoge3

tests:
  hoge3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hoge3
